# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 22:22
from __future__ import unicode_literals

import os

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personCode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('img', models.FileField(blank=True, default=os.path.join(settings.BASE_DIR,
                                                                          "election/static/images/placeholder.png"),
                                         null=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='SubElection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short', models.CharField(default='', max_length=10)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='sub_election',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='election.SubElection'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='choice',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='election.Candidate'),
        ),
    ]
