# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subelection',
            name='is_multi_selectable',
            field=models.BooleanField(default=False),
        ),
    ]
