# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_candidate_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubElection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='ballot',
            name='aejChoose',
        ),
        migrations.RemoveField(
            model_name='ballot',
            name='ptChoose',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='election_type',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='result',
        ),
        migrations.AddField(
            model_name='ballot',
            name='choice',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='election.Candidate'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='election/static/images/upload/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='sub_election',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='election.SubElection'),
        ),
    ]
