# Generated by Django 2.1.2 on 2018-10-18 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('election', '0004_auto_20181016_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionuser',
            name='election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='election.Election'),
        ),
    ]
