# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_auto_20170206_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='static/images/upload/'),
        ),
    ]
