# Generated by Django 2.1.2 on 2018-11-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('election', '0005_auto_20181018_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='active',
        ),
        migrations.AddField(
            model_name='election',
            name='state',
            field=models.IntegerField(choices=[(1, 'not active'), (2, 'active'), (3, 'closed')], default=1),
        ),
    ]
