# Generated by Django 2.1.2 on 2018-11-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('election', '0006_auto_20181117_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='saved_votes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
