# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0008_auto_20170207_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='img',
            field=models.FileField(blank=True, default='election/static/images/placeholder.png', null=True, upload_to='uploads/'),
        ),
    ]
