# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0011_auto_20170211_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='subelection',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
