app = "ebu-breakfast"

[env]
  DEBUG = "False"
  ASGI_THREADS = 15

[deploy]
  release_command = "python manage.py migrate --no-input"

[processes]
  app = "gunicorn breakfast.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8080"

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 50
    soft_limit = 40
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
