name: Django CI

on:
  push 

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: breakfast
          POSTGRES_PASSWORD: github-password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
    - name: "Checkout"
      uses: actions/checkout@v3

    - name: "Set up Python 3.9.12"
      uses: actions/setup-python@v3
      with:
        python-version: 3.9.12

    - name: "Install Poetry"
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: "Set up Node 10"
      uses: actions/setup-node@v3
      with:
        node-version: 10

    - name: "Install Dependencies"
      run: | 
        poetry install
        npm install

    - name: "Build Frontend"
      run: | 
        npm run build
        poetry run python manage.py collectstatic

    - name: "Run Tests"
      run: poetry run python manage.py test
      env:
        DATABASE_URL: postgres://postgres:github-password@localhost:5432/breakfast
